package bean;
// Generated 19/10/2023 14:37:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GasCompra generated by hbm2java
 */
@Entity
@Table(name="gas_compra"
    ,catalog="db_geovane_silva"
)
public class GasCompra  implements java.io.Serializable {


     private int gasIdcompra;
     private Date gasDataCompra;
<<<<<<< HEAD
<<<<<<< HEAD
     private int gasValorTotal;
=======
     private int gasValorTOtal;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
=======
     private int gasValorTOtal;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
     private String gasFormaDePagamento;
     private int gasNumeroDaFatura;

    public GasCompra() {
    }

	
    public GasCompra(int gasIdcompra) {
        this.gasIdcompra = gasIdcompra;
    }
<<<<<<< HEAD
<<<<<<< HEAD
    public GasCompra(int gasIdcompra, Date gasDataCompra, int gasValorTotal, String gasFormaDePagamento, int gasNumeroDaFatura) {
       this.gasIdcompra = gasIdcompra;
       this.gasDataCompra = gasDataCompra;
       this.gasValorTotal = gasValorTotal;
=======
=======
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
    public GasCompra(int gasIdcompra, Date gasDataCompra, int gasValorTOtal, String gasFormaDePagamento, int gasNumeroDaFatura) {
       this.gasIdcompra = gasIdcompra;
       this.gasDataCompra = gasDataCompra;
       this.gasValorTOtal = gasValorTOtal;
<<<<<<< HEAD
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
=======
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
       this.gasFormaDePagamento = gasFormaDePagamento;
       this.gasNumeroDaFatura = gasNumeroDaFatura;
    }
   
     @Id 

    
    @Column(name="gas_idcompra", unique=true, nullable=false)
    public int getGasIdcompra() {
        return this.gasIdcompra;
    }
    
    public void setGasIdcompra(int gasIdcompra) {
        this.gasIdcompra = gasIdcompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gas_data_compra", length=10)
    public Date getGasDataCompra() {
        return this.gasDataCompra;
    }
    
    public void setGasDataCompra(Date gasDataCompra) {
        this.gasDataCompra = gasDataCompra;
    }

    
<<<<<<< HEAD
<<<<<<< HEAD
    @Column(name="gas_valor_total")
    public int getGasValorTotal() {
        return this.gasValorTotal;
    }
    
    public void setGasValorTotal(int gasValorTotal) {
        this.gasValorTotal = gasValorTotal;
=======
=======
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
    @Column(name="gas_valor t_otal")
    public int getGasValorTOtal() {
        return this.gasValorTOtal;
    }
    
    public void setGasValorTOtal(int gasValorTOtal) {
        this.gasValorTOtal = gasValorTOtal;
<<<<<<< HEAD
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
=======
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
    }

    
    @Column(name="gas_forma_de_pagamento", length=45)
    public String getGasFormaDePagamento() {
        return this.gasFormaDePagamento;
    }
    
    public void setGasFormaDePagamento(String gasFormaDePagamento) {
        this.gasFormaDePagamento = gasFormaDePagamento;
    }

    
    @Column(name="gas_numero_da_fatura")
    public int getGasNumeroDaFatura() {
        return this.gasNumeroDaFatura;
    }
    
    public void setGasNumeroDaFatura(int gasNumeroDaFatura) {
        this.gasNumeroDaFatura = gasNumeroDaFatura;
    }




}


