package bean;
// Generated 19/10/2023 14:37:53 by Hibernate Tools 4.3.1


<<<<<<< HEAD
<<<<<<< HEAD
=======
import java.util.HashSet;
import java.util.Set;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
=======
import java.util.HashSet;
import java.util.Set;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
<<<<<<< HEAD
<<<<<<< HEAD
=======
import javax.persistence.OneToMany;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
=======
import javax.persistence.OneToMany;
>>>>>>> 73bfd72e5a9a447735fa1425ee65e26daf609117
import javax.persistence.Table;

/**
 * GasProduto generated by hbm2java
 */
@Entity
@Table(name="gas_produto"
    ,catalog="db_geovane_silva"
)
public class GasProduto  implements java.io.Serializable {


     private int gasIdproduto;
     private GasFornecedor gasFornecedor;
     private GasTipo gasTipo;
     private int gasValor;
     private String gasNome;

    public GasProduto() {
    }


    public GasProduto(int gasIdproduto, GasFornecedor gasFornecedor, GasTipo gasTipo, int gasValor, String gasNome) {
       this.gasIdproduto = gasIdproduto;
       this.gasFornecedor = gasFornecedor;
       this.gasTipo = gasTipo;
       this.gasValor = gasValor;
       this.gasNome = gasNome;
    }
   
     @Id 

    
    @Column(name="gas_idproduto", unique=true, nullable=false)
    public int getGasIdproduto() {
        return this.gasIdproduto;
    }
    
    public void setGasIdproduto(int gasIdproduto) {
        this.gasIdproduto = gasIdproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_fornecedor", nullable=false)
    public GasFornecedor getGasFornecedor() {
        return this.gasFornecedor;
    }
    
    public void setGasFornecedor(GasFornecedor gasFornecedor) {
        this.gasFornecedor = gasFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gas_fk_tipoo", nullable=false)
    public GasTipo getGasTipo() {
        return this.gasTipo;
    }
    
    public void setGasTipo(GasTipo gasTipo) {
        this.gasTipo = gasTipo;
    }

    
    @Column(name="gas_valor")
    public int getGasValor() {
        return this.gasValor;
    }
    
    public void setGasValor(int gasValor) {
        this.gasValor = gasValor;
    }

    
    @Column(name="gas_nome", length=45)
    public String getGasNome() {
        return this.gasNome;
    }
    
    public void setGasNome(String gasNome) {
        this.gasNome = gasNome;
    }





}


